import type {Metadata} from "next"
import '@/shared/styles/globals.css'
import Footer from "@/widgets/footer/Footer"
import Header from "@/widgets/header/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(
  {children}: Readonly<{children: React.ReactNode}>
){
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
