"""replace int to enum from construction_quarter in project

Revision ID: 0b894a74af7e
Revises: 11f006d1604a
Create Date: 2025-04-14 11:30:43.150102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b894a74af7e'
down_revision: Union[str, None] = '11f006d1604a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    quarterenum = sa.Enum(
        'I квартал', 'II квартал', 'III квартал', 'IV квартал', name='quarterenum'
    )
    quarterenum.create(op.get_bind())
    op.alter_column('projects', 'construction_quarter',
                    existing_type=sa.INTEGER(),
                    type_=quarterenum,
                    postgresql_using="construction_quarter::text::quarterenum",
                    nullable=True)  # Оставляем nullable
    op.execute(
        "UPDATE projects SET construction_quarter = 'I квартал' "
        "WHERE construction_quarter IS NULL"
    )
    op.alter_column('projects', 'construction_quarter',
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'construction_quarter',
                    existing_type=sa.Enum(
                        'I квартал',
                        'II квартал',
                        'III квартал',
                        'IV квартал',
                        name='quarterenum'
                    ),
                    type_=sa.INTEGER(),
                    postgresql_using="construction_quarter::text::integer",
                    nullable=True)
    quarterenum = sa.Enum(name='quarterenum')
    quarterenum.drop(op.get_bind())
    # ### end Alembic commands ###
