"""add field accept

Revision ID: 0c4f1665b6cf
Revises: 7e52d3ac4032
Create Date: 2025-04-15 12:05:30.915666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4f1665b6cf'
down_revision: Union[str, None] = '7e52d3ac4032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('accept', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'accept')
    # ### end Alembic commands ###
