"""replace construction_date in project

Revision ID: 11f006d1604a
Revises: 094df34a1a62
Create Date: 2025-04-14 11:17:11.845907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f006d1604a'
down_revision: Union[str, None] = '094df34a1a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('construction_year', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('construction_quarter', sa.Integer(), nullable=True))
    op.drop_column('projects', 'construction_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('construction_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'construction_quarter')
    op.drop_column('projects', 'construction_year')
    # ### end Alembic commands ###
