"""new_model zone and relations with apartment

Revision ID: 2ba6a76f8268
Revises: 36f476289576
Create Date: 2025-03-02 01:58:28.100842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba6a76f8268'
down_revision: Union[str, None] = '36f476289576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('apartments', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'apartments', 'zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_column('apartments', 'zone_id')
    op.drop_table('zones')
    # ### end Alembic commands ###
