"""del ondelete from project-projectimage

Revision ID: 2d7860ab8389
Revises: bd139f32303a
Create Date: 2025-04-09 22:11:12.428973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7860ab8389'
down_revision: Union[str, None] = 'bd139f32303a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_images_project_id_fkey', 'project_images', type_='foreignkey')
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.create_foreign_key('project_images_project_id_fkey', 'project_images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
