"""new_column rooms

Revision ID: 36f476289576
Revises: 62a3314fc63c
Create Date: 2025-03-02 01:12:24.784682

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f476289576'
down_revision: Union[str, None] = '62a3314fc63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_type = postgresql.ENUM('studio', '1', '2', '3', '4', '5', name='countrooms')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type.create(op.get_bind())

    op.add_column('apartments', sa.Column('rooms_count', enum_type, nullable=True))
    op.execute("UPDATE apartments SET rooms_count = 'studio' WHERE rooms_count IS NULL")
    op.alter_column('apartments', 'rooms_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'rooms_count')
    enum_type.drop(op.get_bind())
    # ### end Alembic commands ###
