"""initial

Revision ID: 41f69a204161
Revises: 
Create Date: 2025-03-04 03:39:13.375691

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa

from app.core.config import APARTMENTS_IMAGE

# revision identifiers, used by Alembic.
revision: str = '41f69a204161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('rooms_count', sa.Enum('studio', '1', '2', '3', '4', '5', name='countrooms'), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discounted_price', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('image', fastapi_storages.integrations.sqlalchemy.FileType(storage=APARTMENTS_IMAGE), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    op.drop_table('zones')
    # ### end Alembic commands ###
