"""initial

Revision ID: 62a3314fc63c
Revises: 
Create Date: 2025-03-01 23:41:11.140031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages

from app.core.config import APARTMENTS_IMAGE

# revision identifiers, used by Alembic.
revision: str = '62a3314fc63c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('image', fastapi_storages.integrations.sqlalchemy.FileType(storage=APARTMENTS_IMAGE), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discounted_price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    # ### end Alembic commands ###
