"""optional null question

Revision ID: 7e52d3ac4032
Revises: bb3614c28182
Create Date: 2025-04-15 11:40:45.623024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e52d3ac4032'
down_revision: Union[str, None] = 'bb3614c28182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
