"""add table ApartmentVisit

Revision ID: 84984a6d68d6
Revises: 0c4f1665b6cf
Create Date: 2025-04-15 13:10:39.304868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84984a6d68d6'
down_revision: Union[str, None] = '0c4f1665b6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accept', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('date_visit', sa.DateTime(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_visits')
    # ### end Alembic commands ###
