"""add city table

Revision ID: 849c25bfa4c8
Revises: 2d7860ab8389
Create Date: 2025-04-12 21:04:38.029323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849c25bfa4c8'
down_revision: Union[str, None] = '2d7860ab8389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'city')
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('projects', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
