"""add cascade ap - proj

Revision ID: 84b979bc0269
Revises: 849c25bfa4c8
Create Date: 2025-04-12 21:10:48.213245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b979bc0269'
down_revision: Union[str, None] = '849c25bfa4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apartments_project_id_fkey', 'apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.create_foreign_key('apartments_project_id_fkey', 'apartments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
