"""del col image_url from apartments

Revision ID: b6d470a49966
Revises: 41f69a204161
Create Date: 2025-03-04 14:43:34.845082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d470a49966'
down_revision: Union[str, None] = '41f69a204161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
