"""add field created_ad to table question

Revision ID: bb3614c28182
Revises: 4c95c0d3c512
Create Date: 2025-04-15 11:11:53.744516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3614c28182'
down_revision: Union[str, None] = '4c95c0d3c512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
