"""delete_district

Revision ID: d652f944f38b
Revises: f76e5f109b0d
Create Date: 2025-04-03 14:32:14.791918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd652f944f38b'
down_revision: Union[str, None] = 'f76e5f109b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
