"""delete address from zone model

Revision ID: e38a0d677a54
Revises: 2ba6a76f8268
Create Date: 2025-03-02 02:04:35.932518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38a0d677a54'
down_revision: Union[str, None] = '2ba6a76f8268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
